/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ApiPublicNexoraTickRouteImport } from './routes/api/public/nexora/tick'
import { Route as ApiPublicTelegramAnnounceRouteImport } from './routes/api/public/telegram/announce'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNexoraTickRoute = ApiPublicNexoraTickRouteImport.update({
  id: '/api/public/nexora/tick',
  path: '/api/public/nexora/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramAnnounceRoute =
  ApiPublicTelegramAnnounceRouteImport.update({
    id: '/api/public/telegram/announce',
    path: '/api/public/telegram/announce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/share': typeof ShareRoute
  '/api/public/nexora/tick': typeof ApiPublicNexoraTickRoute
  '/api/public/telegram/announce': typeof ApiPublicTelegramAnnounceRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/share': typeof ShareRoute
  '/api/public/nexora/tick': typeof ApiPublicNexoraTickRoute
  '/api/public/telegram/announce': typeof ApiPublicTelegramAnnounceRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/share': typeof ShareRoute
  '/api/public/nexora/tick': typeof ApiPublicNexoraTickRoute
  '/api/public/telegram/announce': typeof ApiPublicTelegramAnnounceRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/share'
    | '/api/public/nexora/tick'
    | '/api/public/telegram/announce'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/share'
    | '/api/public/nexora/tick'
    | '/api/public/telegram/announce'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/share'
    | '/api/public/nexora/tick'
    | '/api/public/telegram/announce'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ShareRoute: typeof ShareRoute
  ApiPublicNexoraTickRoute: typeof ApiPublicNexoraTickRoute
  ApiPublicTelegramAnnounceRoute: typeof ApiPublicTelegramAnnounceRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nexora/tick': {
      id: '/api/public/nexora/tick'
      path: '/api/public/nexora/tick'
      fullPath: '/api/public/nexora/tick'
      preLoaderRoute: typeof ApiPublicNexoraTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/announce': {
      id: '/api/public/telegram/announce'
      path: '/api/public/telegram/announce'
      fullPath: '/api/public/telegram/announce'
      preLoaderRoute: typeof ApiPublicTelegramAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ShareRoute: ShareRoute,
  ApiPublicNexoraTickRoute: ApiPublicNexoraTickRoute,
  ApiPublicTelegramAnnounceRoute: ApiPublicTelegramAnnounceRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
